FROM --platform=linux/amd64 node:18 AS deps
WORKDIR /app

COPY package.json package-lock.json ./
COPY  ./next.config.js ./
COPY  ./next-i18next.config.js ./
RUN  npm install --production

FROM --platform=linux/amd64 node AS builder
WORKDIR /app
COPY --from=deps /app/node_modules ./node_modules
COPY --from=deps  /app/next.config.js ./next.config.js 
COPY --from=deps  /app/next-i18next.config.js ./next-i18next.config.js
COPY . .

ENV NEXT_TELEMETRY_DISABLED 1

RUN npm run build

FROM --platform=linux/amd64 node AS runner
WORKDIR /app

ENV NODE_ENV production
ENV NEXT_TELEMETRY_DISABLED 1

RUN addgroup --system --gid 1001 nodejs
RUN adduser --system --uid 1001 nextjs

COPY --from=builder --chown=nextjs:nodejs /app/.next ./.next
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/package.json ./package.json
COPY --from=builder /app/next.config.js ./next.config.js
COPY --from=builder /app/next-i18next.config.js ./next-i18next.config.js

USER nextjs

EXPOSE 3000

CMD ["npm", "start"]